name: VS Code Extension Build (Manual Review Recommended)

on:
  push:
    branches: [ main ]  # Adjust based on your trigger branch(es)

jobs:
  build:
    runs-on: ubuntu-latest  # Adjust OS as needed
    steps:
      - uses: actions/checkout@v3  # Checkout code from repository

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Adjust Node.js version if required

      - name: Install dependencies
        run: npm install

      - name: Build extension
        run: npm run vsce  # Assuming vsce script builds the extension

      - name: Extract release information (optional)
        run: |  # Example for extracting version from package.json
          VERSION=$(jq -r '.version' package.json)
          echo "Release version: $VERSION"

      - name: Generate release assets (build .vsix)
        run: |  # Example assuming vsce builds the .vsix file
          if [[ -f ./out/*.vsix ]]; then
            echo "Release asset (.vsix) found in ./out"
          else
            echo "**WARNING:** No .vsix file found in ./out. Release might be incomplete."
          fi

      - name: Manual Review and Upload (Recommended)
        uses: actions/hub-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false

